name: Release_Version

on:
  pull_request:
    types: [closed] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
    - name: Pull request merged
      if: github.event.pull_request.merged == true
      run: |
          echo merged
          git config user.email "gh-actions@lbcustommongo.gh"
          git config user.name "GH-Actions-Bot"
          npm i -g np
          np minor --yolo
